# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalRevision',
            new_name='AuditTransaction',
        ),
    ]
