# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0003_auto_20161119_1758'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
